name: Deploy to NCP

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure NCP credentials with AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NCP_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NCP_SECRET_ACCESS_KEY }}
          aws-region: 'kr-standard'

      - name: Upload to Object Storage
        run: >
          aws --endpoint-url=https://kr.object.ncloudstorage.com s3
            cp ./build s3://${{ secrets.NCP_BUCKET_NAME }} --recursive

      - name: Make all files public
        run: >
          aws --endpoint-url=https://kr.object.ncloudstorage.com/ s3
            ls s3://${{ secrets.NCP_BUCKET_NAME }} --recursive
            | awk '{cmd="aws --endpoint-url=https://kr.object.ncloudstorage.com/ s3api put-object-acl --bucket ${{ secrets.NCP_BUCKET_NAME }} --acl public-read --key "$4; system(cmd)}'
